# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'cfa11056-7e92-4d1c-b038-4e73ead5b736'
    subscriptionId: 'f596f200-d524-4716-b18d-2c7d1d905c83'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'ARMPipeline-rg'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'https://raw.githubusercontent.com/bragic/BragicARMTemplates/refs/heads/main/ARMStorage/createStorage.json'
    overrideParameters: '-storageAccounts_name storage4wendito'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
